name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-11-jdk python3-pip python3-setuptools python3-wheel
        pip install --upgrade pip
        pip install cython==0.29.36
        pip install buildozer==1.4.7

    - name: Download Android SDK/NDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $HOME/Android
        mkdir -p $HOME/Android/cmdline-tools/latest
        mv $HOME/Android/cmdline-tools/* $HOME/Android/cmdline-tools/latest/
        yes | $HOME/Android/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/Android "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Build APK
      run: |
        export ANDROID_HOME=$HOME/Android
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
        export BUILDOZER_ALLOW_ROOT=1
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: myapp-apk
        path: bin/*.apk
